#!/bin/bash
while :
do
#SMU Rastgele sayı sınıfı
#################################
echo -e "Rastgele Sayı Üretiliyor"
RANGE=254
number=$RANDOM
let "number %= $RANGE"
#################################
./go $number
done
